// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo7ItehNparSyhYsmSvKp_mwSnjXJL634',
    appId: '1:692769966091:web:71eeceb37b98e28c659f0e',
    messagingSenderId: '692769966091',
    projectId: 'a-billion-spells',
    authDomain: 'a-billion-spells.firebaseapp.com',
    storageBucket: 'a-billion-spells.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMsdskEBpSWGwzkqkRJMX5uF7k9AxK1Pc',
    appId: '1:692769966091:android:1be978add5e599d1659f0e',
    messagingSenderId: '692769966091',
    projectId: 'a-billion-spells',
    storageBucket: 'a-billion-spells.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC19TXqDHojG9obvDZIDEo0p3gdqXg7tRI',
    appId: '1:692769966091:ios:cb12f208b073367f659f0e',
    messagingSenderId: '692769966091',
    projectId: 'a-billion-spells',
    storageBucket: 'a-billion-spells.appspot.com',
    iosBundleId: 'com.example.aBillionSpells',
  );

}